In [1]:
import numpy as np
A = np.array([[1, 2, 7], [2, 3, 1], [3, 1, 2]])

In [2]:
np.linalg.eigvals(A)

array([ 7.19615242, -3.19615242,  2.        ])

In [3]:
# Power method
x = np.transpose(np.linalg.eigvals(A))
print(x.size)
print(x[0])
print(np.dot(A,x))
for i in range(100):
    r = np.dot(A,x)[0]/x[0]
    print(r)
    x = np.dot(A,x)

3
7.19615242270663
[14.80384758  6.80384758 22.39230485]
2.0571892738933006
12.507402260326828
5.4114999725816775
8.092243923694774
6.803186883268943
7.369291292313336
7.117945084282151
7.230394442848946
7.18077384924756
7.202929975860807
7.193126300019932
7.197491827014157
7.195556193943117
7.196416856047404
7.196034867901334
7.196204604165571
7.196129237983997
7.19616271777537
7.196147849518417
7.196154453692306
7.196151520598373
7.196152823361411
7.1961522447528825
7.196152501743224
7.196152387602428
7.196152438297988
7.196152415781747
7.196152425782295
7.1961524213405825
7.196152423313359
7.196152422437154
7.196152422826321
7.196152422653472
7.1961524227302425
7.196152422696147
7.196152422711289
7.1961524227045635
7.196152422707551
7.1961524227062235
7.196152422706814
7.19615242270655
7.196152422706668
7.196152422706615
7.196152422706639
7.196152422706629
7.196152422706633
7.196152422706632
7.196152422706632
7.196152422706631
7.196152422706633
7.196152422706631
7.196152422706633
7.

In [5]:
# jacobi method
A = np.array([[1, 1/2, -(3**0.5)/2], [1/2, 4, (3**0.5)], [-(3**0.5)/2, (3**0.5), 2]])
print(np.linalg.eigvals(A))
p, q = 1, 2
sheta = -np.pi/6
print(A[p][q], A[q][q], A[p][p], sheta)
U = np.array([[1, 0, 0], [0, np.cos(sheta), np.sin(sheta)], [0, -np.sin(sheta), np.cos(sheta)]])
U_inv = np.linalg.inv(U)
U

[2. 0. 5.]
1.7320508075688772 2.0 4.0 -0.5235987755982988


array([[ 1.       ,  0.       ,  0.       ],
       [ 0.       ,  0.8660254, -0.5      ],
       [ 0.       ,  0.5      ,  0.8660254]])

In [6]:
B = np.dot(np.dot(U_inv, A), U)
B
sheta2 = np.pi/4
U2 = np.array([[np.cos(sheta2), 0, np.sin(sheta2)], [0, 1, 0], [-np.sin(sheta2), 0, np.cos(sheta2)]])
U2

array([[ 0.70710678,  0.        ,  0.70710678],
       [ 0.        ,  1.        ,  0.        ],
       [-0.70710678,  0.        ,  0.70710678]])

In [7]:
U2_inv = np.linalg.inv(U2)
U2_inv
B2 = np.dot(np.dot(U2_inv, B), U2)
B2

array([[ 2.00000000e+00, -2.85283805e-16, -3.58760778e-16],
       [-2.01520370e-16,  5.00000000e+00,  3.48011991e-16],
       [-2.68031548e-16,  4.31775426e-16,  1.11022302e-16]])