In [35]:
import numpy as np
A = np.array([[5, 6, 8], [6, 4, 2], [8, 2, 1]])
s = (sum([A[i][0]**2 for i in range(1, 3)]))**0.5
A

array([[5, 6, 8],
       [6, 4, 2],
       [8, 2, 1]])

In [36]:
np.linalg.eigvals(A)

array([14.65273726, -5.8244616 ,  1.17172434])

In [13]:
v = np.array([0, s + A[0][1], A[0][2]], ndmin=2)
v

array([[ 0., 16.,  8.]])

In [31]:
np.linalg.norm(v)

17.88854381999832

In [15]:
u = v/np.linalg.norm(v)
u

array([[0.        , 0.89442719, 0.4472136 ]])

In [29]:
np.dot(u.transpose(),u)

array([[0. , 0. , 0. ],
       [0. , 0.8, 0.4],
       [0. , 0.4, 0.2]])

In [32]:
I = np.identity(3)
I
P = I - 2*np.dot(u.transpose(),u)
P

array([[ 1. ,  0. ,  0. ],
       [ 0. , -0.6, -0.8],
       [ 0. , -0.8,  0.6]])

In [34]:
A1 = np.dot(np.dot(P, A), P)
A1

array([[ 5.0000000e+00, -1.0000000e+01,  8.8817842e-16],
       [-1.0000000e+01,  4.0000000e+00,  2.0000000e+00],
       [ 8.8817842e-16,  2.0000000e+00,  1.0000000e+00]])