In [4]:
import numpy as np
EPS = 1e-9
N = 3
a = np.array([[0.01, 5.0, 4.9],
    [0.5, 3.0, 2.0],
    [1.0, 5.0, -5.0]])
b=np.array([10,10,10])
print(np.linalg.solve(a,b))

[10.  1.  1.]


In [103]:
# Cramer's rule
deta = np.linalg.det(a)
a0 = a.copy()
x = []
for i in range(len(b)):
    ai = a.copy()
    ai[:,i] = b
    xi = np.linalg.det(ai)/deta
    x.append(xi)
print(x)

[9.996155890892872, 1.0019874861980105, 0.9979797979797987]


In [142]:
a = np.array([[0.01, 5.0, 4.9],
    [0.5, 3.0, 2.0],
    [1.0, 5.0, -5.0]])
b=np.array([10,10,10])

# Gauss-Jacobi-Elimination
def printsys():
    for i in range(3):
        print("{}x1 + {}x2 + {}x3 ={}".format(a[i][0], a[i][1], a[i][2], b[i]))
    print()
    return
printsys()

# Forward elimination
for k in range(N):
    # TODO:pivotting
#     print(a[k:,k:k+1])
#     print(k)
    targi = np.argmax(a[k:,k:k+1]) + k
#     print("max index" + str(targi))
#     printsys()
    a[k], a[targi] = a[targi].copy(), a[k].copy()
    b[k], b[targi] = b[targi].copy(), b[k].copy()
#     printsys()
    for i in range(k+1, N):
        m = a[i][k]/a[k][k]
        for j in range(k, N):
            a[i][j] -=  m*a[k][j]
            if abs(a[i][j]) < EPS:
                a[i][j] = 0
        b[i] = b[i] - m*b[k]
        if abs(b[i]) < EPS:
            b[i] = 0
    print("eliminated")
    printsys()
print(a, b)
# back substitution
res = []
for k in range(N-1, -1, -1):
    sum_ax = 0
    for i in range(N-1, k, -1):
        sum_ax += a[k][i]*res[N-i-1]
    res.append((b[k]-sum_ax)/a[k][k])
print(res[::-1])

0.01x1 + 5.0x2 + 4.9x3 =10
0.5x1 + 3.0x2 + 2.0x3 =10
1.0x1 + 5.0x2 + -5.0x3 =10

eliminated
1.0x1 + 5.0x2 + -5.0x3 =10
0.0x1 + 0.5x2 + 4.5x3 =5
0.0x1 + 4.95x2 + 4.95x3 =9

eliminated
1.0x1 + 5.0x2 + -5.0x3 =10
0.0x1 + 4.95x2 + 4.95x3 =9
0.0x1 + 0.0x2 + 4.0x3 =4

eliminated
1.0x1 + 5.0x2 + -5.0x3 =10
0.0x1 + 4.95x2 + 4.95x3 =9
0.0x1 + 0.0x2 + 4.0x3 =4

[[ 1.    5.   -5.  ]
 [ 0.    4.95  4.95]
 [ 0.    0.    4.  ]] [10  9  4]
[10.90909090909091, 0.8181818181818181, 1.0]


In [5]:
from scipy.linalg import lu_factor, lu_solve
import numpy as np
# LU-decomposition
a = np.array([[0.01, 5.0, 4.9],
    [0.5, 3.0, 2.0],
    [1.0, 5.0, -5.0]])
b = np.array([10,10,10])
L = np.identity(3)

swapped = {}
for k in range(N):
    # pivoting
#     targi = np.argmax(a[k:,k:k+1]) + k
#     swapped[k] = targi
#     swapped[targi] = k
#     a[k], a[targi] = a[targi].copy(), a[k].copy()
#     b[k], b[targi] = b[targi].copy(), b[k].copy()
    for i in range(k+1, N):
        m = a[i][k]/a[k][k]
        L[i][k] = m
        for j in range(k, N):
            a[i][j] -=  m*a[k][j]
            if abs(a[i][j]) < EPS:
                a[i][j] = 0
U = a
print(L)
print(U)
print(np.dot(L,U))

[[  1.           0.           0.        ]
 [ 50.           1.           0.        ]
 [100.           2.00404858   1.        ]]
[[ 1.00000000e-02  5.00000000e+00  4.90000000e+00]
 [ 0.00000000e+00 -2.47000000e+02 -2.43000000e+02]
 [ 0.00000000e+00  0.00000000e+00 -8.01619433e+00]]
[[ 0.01  5.    4.9 ]
 [ 0.5   3.    2.  ]
 [ 1.    5.   -5.  ]]


In [153]:
# forward substitution
ys = []
for k in range(N):
    sum_l_y = 0
    for i in range(k):
        sum_l_y += L[k][i]*ys[i]
    ys.append((b[k]-sum_l_y)/L[k][k])

print(ys)

# back substitution
xs = []
for k in range(N-1, -1, -1):
    sum_u_x = 0
    for i in range(N-1, k, -1):
        sum_u_x += U[k][i]*xs[N-i-1]
    xs.append((ys[k]-sum_u_x)/U[k][k])
print(xs[::-1])
LU = lu(np.array([[0.01, 5.0, 4.9],
    [0.5, 3.0, 2.0],
    [1.0, 5.0, -5.0]]))
LU

[10.0, 20.0, 8.78989898989899]
[11.772727272727273, 1.8429292929292926, 2.1974747474747476]


(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]), array([[1.       , 0.       , 0.       ],
        [0.01     , 1.       , 0.       ],
        [0.5      , 0.1010101, 1.       ]]), array([[ 1.  ,  5.  , -5.  ],
        [ 0.  ,  4.95,  4.95],
        [ 0.  ,  0.  ,  4.  ]]))

In [4]:
# jacobi法
import numpy as np

ITERATION_LIMIT = 1000

# initialize the matrix
A = np.array([[10., -1., 2., 0.],
              [-1., 11., -1., 3.],
              [2., -1., 10., -1.],
              [0.0, 3., -1., 8.]])
# initialize the RHS vector
b = np.array([6., 25., -11., 15.])

# prints the system
print("System:")
for i in range(A.shape[0]):
    row = ["{}*x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
    print(" + ".join(row), "=", b[i])
print()

x = np.zeros_like(b)
for it_count in range(ITERATION_LIMIT):
    print("Current solution:", x)
    x_new = np.zeros_like(x)
    print("iterator",it_count)
    print(x)
    for i in range(A.shape[0]):
        print("update",i)

        s1 = np.dot(A[i, :i], x[:i])
        print(A[i, :i])
        print(x[:i])
        s2 = np.dot(A[i, i + 1:], x[i + 1:])
        print(A[i, i + 1:])
        print(x[i + 1:])
        x_new[i] = (b[i] - s1 - s2) / A[i, i]

    if np.allclose(x, x_new, atol=1e-10, rtol=0.):
        break

    x = x_new

print("Solution:")
print(x)
error = np.dot(A, x) - b
print("Error:")
print(error)

System:
10.0*x1 + -1.0*x2 + 2.0*x3 + 0.0*x4 = 6.0
-1.0*x1 + 11.0*x2 + -1.0*x3 + 3.0*x4 = 25.0
2.0*x1 + -1.0*x2 + 10.0*x3 + -1.0*x4 = -11.0
0.0*x1 + 3.0*x2 + -1.0*x3 + 8.0*x4 = 15.0

Current solution: [0. 0. 0. 0.]
iterator 0 0
[]
[]
[-1.  2.  0.]
[0. 0. 0.]
iterator 0 1
[-1.]
[0.]
[-1.  3.]
[0. 0.]
iterator 0 2
[ 2. -1.]
[0. 0.]
[-1.]
[0.]
iterator 0 3
[ 0.  3. -1.]
[0. 0. 0.]
[]
[]
Current solution: [ 0.6         2.27272727 -1.1         1.875     ]
iterator 1 0
[]
[]
[-1.  2.  0.]
[ 2.27272727 -1.1         1.875     ]
iterator 1 1
[-1.]
[0.6]
[-1.  3.]
[-1.1    1.875]
iterator 1 2
[ 2. -1.]
[0.6        2.27272727]
[-1.]
[1.875]
iterator 1 3
[ 0.  3. -1.]
[ 0.6         2.27272727 -1.1       ]
[]
[]
Current solution: [ 1.04727273  1.71590909 -0.80522727  0.88522727]
iterator 2 0
[]
[]
[-1.  2.  0.]
[ 1.71590909 -0.80522727  0.88522727]
iterator 2 1
[-1.]
[1.04727273]
[-1.  3.]
[-0.80522727  0.88522727]
iterator 2 2
[ 2. -1.]
[1.04727273 1.71590909]
[-1.]
[0.88522727]
iterator 2 3
[ 0.  

In [2]:
# gauss-seidel
import numpy as np

ITERATION_LIMIT = 1000

# initialize the matrix
A = np.array([[10., -1., 2., 0.],
              [-1., 11., -1., 3.],
              [2., -1., 10., -1.],
              [0., 3., -1., 8.]])
# initialize the RHS vector
b = np.array([6., 25., -11., 15.])

print("System of equations:")
for i in range(A.shape[0]):
    row = ["{0:3g}*x{1}".format(A[i, j], j + 1) for j in range(A.shape[1])]
    print("[{0}] = [{1:3g}]".format(" + ".join(row), b[i]))

x = np.zeros_like(b)
for it_count in range(1, ITERATION_LIMIT):
    x_new = np.zeros_like(x)
    print("Iteration {0}: {1}".format(it_count, x))
    for i in range(A.shape[0]):
        s1 = np.dot(A[i, :i], x_new[:i])
        s2 = np.dot(A[i, i + 1:], x[i + 1:])
        x_new[i] = (b[i] - s1 - s2) / A[i, i]
    if np.allclose(x, x_new, rtol=1e-8):
        break
    x = x_new

print("Solution: {0}".format(x))
error = np.dot(A, x) - b
print("Error: {0}".format(error))

System of equations:
[ 10*x1 +  -1*x2 +   2*x3 +   0*x4] = [  6]
[ -1*x1 +  11*x2 +  -1*x3 +   3*x4] = [ 25]
[  2*x1 +  -1*x2 +  10*x3 +  -1*x4] = [-11]
[  0*x1 +   3*x2 +  -1*x3 +   8*x4] = [ 15]
Iteration 1: [0. 0. 0. 0.]
Iteration 2: [ 0.6         2.32727273 -0.98727273  0.87886364]
Iteration 3: [ 1.03018182  2.03693802 -1.0144562   0.98434122]
Iteration 4: [ 1.00658504  2.00355502 -1.00252738  0.99835095]
Iteration 5: [ 1.00086098  2.00029825 -1.00030728  0.99984975]
Iteration 6: [ 1.00009128  2.00002134 -1.00003115  0.9999881 ]
Iteration 7: [ 1.00000836  2.00000117 -1.00000275  0.99999922]
Iteration 8: [ 1.00000067  2.00000002 -1.00000021  0.99999996]
Iteration 9: [ 1.00000004  1.99999999 -1.00000001  1.        ]
Iteration 10: [ 1.  2. -1.  1.]
Solution: [ 1.  2. -1.  1.]
Error: [ 2.06480930e-08 -1.25551054e-08  3.61417563e-11  0.00000000e+00]
